#!/bin/bash
#--------------------------
# SCRIPT TOP-SSH
# CANAL TELEGRAM: @jhona70
#--------------------------
claro
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install curl -y &>/dev/null
apt install git -y &>/dev/null
apt install figlet boxes -y &>/dev/null
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"| lolcat
rm $HOME/Plus > /dev/null 2>&1; saída 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*ne!v89e032:3r'| sed -e 's/[^az.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^az/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^az/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
toque em $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne " \033[1;33mAGUARDE \033[1;37m- \033[1;33m["| lolcat
enquanto verdadeiro; fazer
for((i=0; i<18; i++)); fazer
echo -ne "\033[1;31m#"
dormir 0,1s
feito
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
dormir 1s
tput cuu1
tput dl1
echo -ne " \033[1;33mAGUARDE \033[1;37m- \033[1;33m["| lolcat
feito
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"| lolcat
tput cnorm
}
função verificar_chave () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/lista" ]] && {
echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
dormir 2
claro; saída 1
}
}
system=$(cat /etc/issue.net)
data=$(data '+%Y-%m-%d <> %H:%M:%S')
eco ""
echo -e "\033[1;37m $sistema $data"| lolcat
figlet 'NITY HÍBRIDO' | caixas -d pedra -p a0v0 | lolcat
echo "SE VOCÊ NÃO PUDER SE DESTACAR PELO TALENTO, VENÇA PELO ESFORÇO."| lolcat
echo -e \033[0m"| lolcat
eco ""
eco ""
echo -e " \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"| lolcat
eco ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mDEBIAN 9 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m \033[1;33m\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"| lolcat
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA (V2RAY) EVITEM OUTROS SISTEMAS\033[0m"| lolcat
echo -e "\033[1;31m \033[1;33m\033[0m"| lolcat
eco ""
\033[0m"| lolcat
eco ""
echo -ne "\033[1;36mINFORME SUA KEY:\033[1;37m "| lolcat; chave de leitura_
se [[-z $_key_]]; então
eco ""
echo -e "\033[1;31m CHAVE INVALIDA\033[1;32m"
dormir 1
claro; saída
fi
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config > /dev/null 2>&1
reinicialização do ssh do serviço > /dev/null 2>&1
echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m $_key_\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink http://191.252.222.34/$_key_/list > /dev/null 2>&1; verif_key
dormir 3s
echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
dormir 3s
#!COLOQUE SEU CÓDIGO DAQUI PARA BAIXO\/


#!/bin/bash
claro
#--------------------------
# SCRIPR TOP SSH ULTMATE
# @jhona70
#--------------------------

# - Núcleos
VERMELHO='\033[1;31m'
AMARELO='\033[1;33m'
SCOLOR='\033[0m'

# - Verifica Execução Como Root
[[ "$EUID" -ne 0 ]] && {
    echo -e "{RED}[x] EXECUTAR COMO USUARIO ROOT !{SCOLOR}"
    saída 1
}

# - Verifica Arquitetura Compatível
case "$(uname -m)" em
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] ARQUITETURA INCOMPATIVA !${SCOLOR}"
        saída 1
        ;;
esac

# - Verifica OS Compatível
if grep -qs "ubuntu" /etc/os-release; então
	os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    [[ "$os_version" -lt 1804 ]] && {
        echo -e "${RED}[x] VERSAO DO UBUNTU INCOMPATIVEL !\n${YELLOW}[!] REQUER UBUNTU 18.04 OU SUPERIOR !${SCOLOR}"
        saída 1
    }
elif [[ -e /etc/debian_version ]]; então
	os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
    [[ "$os_version" -lt 9 ]] && {
        echo -e "${RED}[x] VERSAO DO DEBIAN INCOMPATIVEL !\n${YELLOW}[!] REQUER DEBIAN 9 OU SUPERIOR !${SCOLOR}"
        saída 1
    }
outro
    echo -e "${RED}[x] SO INCOMPATÍVEL !\n${YELLOW}[!] REQUER DISTRO BASE DEBIAN/UBUNTU !${SCOLOR}"
    saída 1
fi

# - Lista Atualizada/Pacotes/Sistema
dpkg --configure -a
atualização do apt -y && atualização do apt -y
apt install descompacte python3 -y

# - Desabilita ipv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

# - Execulta instalador
[[ -e Mais ]] && rm Mais
wget raw.githubusercontent.com/gustavossh/SSHPLUS/main/script/${arch}/Plus && chmod 777 Plus && ./Plus