#!/bin/bash
clear
[[ $(screen -list| grep -c 'bot_auto') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     ATIVACÃO BOT SSH TESTE     \E[0m"
    echo ""
    echo -ne "\n\033[1;32mINFORME O TOKEN\033[1;37m: "; read token
    [[ -z $token ]] && {
        echo "INFORME O TOKEN !"
        exit 0
    }
    echo -ne "\n\033[1;32mINFORME O DOMINIO\033[1;37m: "; read domain
    [[ -z $domain ]] && {
        echo "INFORME O DOMINIO !"
        exit 0
    }
    cd $HOME/BOT
    screen -dmS bot_auto ./bot $token $domain> /dev/null 2>&1
    clear && echo "BOT ATIVADO"
} || {
    screen -r -S "bot_auto" -X quit
    clear && echo "BOT DESATIVADO"
}