#!/bin/bash
    clear
    figlet "BOTS WHATSAPP" | lolcat
    echo -e ""
	echo -e "\033[1;37m 01 ➡️\033[1;36m BOT WHATSAPP & TELEGRAM 💰\033[0m"
    echo -e "\033[1;37m 00 ➡️\033[1;31m SAIR \033[0m"
    echo -e "\033[01;31m\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			16 | 016)
			botssh
			;;
			10| 010)
            inst-botteste
            ;;
            1 | 01)
            terminus
            ;;
            4 | 04)
            botsms
            ;;
            5 | 05)
            botssh
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			esac
			sleep 2
